events {}

http {

    upstream student_servers {
        server student-service-1:5003;
        server student-service-2:5003;
    }

    server {

        listen 80;

        location /student/ {

            proxy_pass http://student_servers/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}